echo "hello User"
echo "----------------------------------"
echo "You are logged onto $(hostname)"
echo "----------------------------------"
echo "Your uptime is:"
echo "$(uptime)"
echo "----------------------------------"
echo "You have the following memory resources."
echo "$(free-m)"
echo "---------------------------------"-
echo "Hard drive space"
echo "$(df-h)"
echo "CPU"
echo "$(cat/proc/cpuinfo)"
echo "$(ifconfig ethO|grep "inet")"
